require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShareItemsController do

  # This should return the minimal set of attributes required to create a valid
  # ShareItem. As you add validations to ShareItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "extract_code" => "9.99" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShareItemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all share_items as @share_items" do
      share_item = ShareItem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:share_items).should eq([share_item])
    end
  end

  describe "GET show" do
    it "assigns the requested share_item as @share_item" do
      share_item = ShareItem.create! valid_attributes
      get :show, {:id => share_item.to_param}, valid_session
      assigns(:share_item).should eq(share_item)
    end
  end

  describe "GET new" do
    it "assigns a new share_item as @share_item" do
      get :new, {}, valid_session
      assigns(:share_item).should be_a_new(ShareItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested share_item as @share_item" do
      share_item = ShareItem.create! valid_attributes
      get :edit, {:id => share_item.to_param}, valid_session
      assigns(:share_item).should eq(share_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ShareItem" do
        expect {
          post :create, {:share_item => valid_attributes}, valid_session
        }.to change(ShareItem, :count).by(1)
      end

      it "assigns a newly created share_item as @share_item" do
        post :create, {:share_item => valid_attributes}, valid_session
        assigns(:share_item).should be_a(ShareItem)
        assigns(:share_item).should be_persisted
      end

      it "redirects to the created share_item" do
        post :create, {:share_item => valid_attributes}, valid_session
        response.should redirect_to(ShareItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved share_item as @share_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShareItem.any_instance.stub(:save).and_return(false)
        post :create, {:share_item => { "extract_code" => "invalid value" }}, valid_session
        assigns(:share_item).should be_a_new(ShareItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShareItem.any_instance.stub(:save).and_return(false)
        post :create, {:share_item => { "extract_code" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested share_item" do
        share_item = ShareItem.create! valid_attributes
        # Assuming there are no other share_items in the database, this
        # specifies that the ShareItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ShareItem.any_instance.should_receive(:update_attributes).with({ "extract_code" => "9.99" })
        put :update, {:id => share_item.to_param, :share_item => { "extract_code" => "9.99" }}, valid_session
      end

      it "assigns the requested share_item as @share_item" do
        share_item = ShareItem.create! valid_attributes
        put :update, {:id => share_item.to_param, :share_item => valid_attributes}, valid_session
        assigns(:share_item).should eq(share_item)
      end

      it "redirects to the share_item" do
        share_item = ShareItem.create! valid_attributes
        put :update, {:id => share_item.to_param, :share_item => valid_attributes}, valid_session
        response.should redirect_to(share_item)
      end
    end

    describe "with invalid params" do
      it "assigns the share_item as @share_item" do
        share_item = ShareItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShareItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => share_item.to_param, :share_item => { "extract_code" => "invalid value" }}, valid_session
        assigns(:share_item).should eq(share_item)
      end

      it "re-renders the 'edit' template" do
        share_item = ShareItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShareItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => share_item.to_param, :share_item => { "extract_code" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested share_item" do
      share_item = ShareItem.create! valid_attributes
      expect {
        delete :destroy, {:id => share_item.to_param}, valid_session
      }.to change(ShareItem, :count).by(-1)
    end

    it "redirects to the share_items list" do
      share_item = ShareItem.create! valid_attributes
      delete :destroy, {:id => share_item.to_param}, valid_session
      response.should redirect_to(share_items_url)
    end
  end

end
